### ISSUE TITLE
REQ: Regenerate MP3 buttons for last comment and all

### ISSUE THREAD

**Issue by mykeehu** [ill13/SpeakLocal#5]
It would be nice if the mp3 files of the last comment or all comments could be regenerated. For the last one, because if I edit the reply, the mp3 is not regenerated, so that would be good, and for all replies, so that there is also sound for the previous dialogs. In this case, the sound tag should be inserted in front of each one in the "visible" block in the JSON file.

**Comment by ill13** [comment]
I believe the current version of TGWUI already has this.on the hamburger menu to the left of the text prompt box.

**Comment by mykeehu** [comment]
You mean the Regenerate button? That will regenerate the last bot post. I was thinking of the TTS sounds, that one click generates the sound for the most recent comment or all comments based on the visible post.

**Comment by ill13** [comment]
This does sound like a great idea, however I feel it's beyond the scope of this extension. This extension is primarily for low-bandwidth data consumption and quick results. 

For example, one could use this in a car so that they can stay hands-free and safe.

If one were to need more options, one could use the JSON text output from my [AutoSave](https://github.com/ill13/AutoSave) extension and send that text to any number of high quality TTS engines, external to TGWUI.

If you are considering using generated speech for other projects, you might want to check [Bark](https://github.com/suno-ai/bark) from *suno-ai*

**Comment by mykeehu** [comment]
That's why I thought of this, because it's offline, so it would regenerate the sounds faster than other online services...

**Comment by ill13** [comment]
I could be wrong, but I believe that *Silero, Bark, Tortise, Coqui* are all AI TTS projects found on GitHub that all can run locally and offline. 

Definitely slower than my extension -but immensely better audio output!

**Comment by mykeehu** [comment]
Thanks for the tips. These are good features, but in Hungarian only coqui could be used via fairseq model, but it's not in oobabooga and I'm not a programmer, so that's it.
Thanks for what you have developed so far, I will give up using TTS for now.
